language: node_js
node_js: 'stable'
branches:
  only:
    - master
    - 1.x

before_install:
  - 'stty cols 80'
  - 'export SAUCE_JOB=react-tether'
  - 'export SAUCE_BUILD=$TRAVIS_COMMIT'

script:
  - ./bin/test
